# For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose

services:
  crawler:
    image: ghcr.io/ttschnz/ahoy-dtu-stats:db_connector
    environment:
      - INVERTER_ENDPOINT=http://ahoy-dtu.fritz.box
      - CRAWLING_INTERVAL=30
      - RUST_LOG=debug
      # - LOGGING_TARGET=stdout
      - LOGGING_TARGET=/output/log
      - DB_URL=mysql://root:password@hostname:3306/db_name
    volumes:
      - ./out:/output
